//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcDemo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AVAILABLE_COURSE
    {
        public AVAILABLE_COURSE()
        {
            this.STUDENTS = new HashSet<STUDENT>();
        }
    
        public int CAMPUS_ID { get; set; }
        public int FACULTY_ID { get; set; }
        public int COURSE_ID { get; set; }
        public int AVAIL_COURSE_ID { get; set; }
    
        public virtual ICollection<STUDENT> STUDENTS { get; set; }
        public virtual CAMPUS_TABLE CAMPUS_TABLE { get; set; }
        public virtual COURSE_TABLE COURSE_TABLE { get; set; }
        public virtual FACULTY_TABLE FACULTY_TABLE { get; set; }
    }
}
