//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcDemo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAMPUS_TABLE
    {
        public CAMPUS_TABLE()
        {
            this.AVAILABLE_COURSE = new HashSet<AVAILABLE_COURSE>();
        }
    
        public int CAMPUS_ID { get; set; }
        public string CAMPUS_NAME { get; set; }
    
        public virtual ICollection<AVAILABLE_COURSE> AVAILABLE_COURSE { get; set; }
    }
}
