//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcDemo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DETAILED_ETHINICITY_TABLE
    {
        public DETAILED_ETHINICITY_TABLE()
        {
            this.STUDENTS = new HashSet<STUDENT>();
        }
    
        public int DETAILED_ETHINICITY_ID { get; set; }
        public string DETAILED_ETHINICITY { get; set; }
        public int ETHINICITY_ID { get; set; }
    
        public virtual ICollection<STUDENT> STUDENTS { get; set; }
        public virtual ETHINICITY_TABLE ETHINICITY_TABLE { get; set; }
    }
}
