//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcDemo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FACULTY_TABLE
    {
        public FACULTY_TABLE()
        {
            this.AVAILABLE_COURSE = new HashSet<AVAILABLE_COURSE>();
            this.COURSE_TABLE = new HashSet<COURSE_TABLE>();
        }
    
        public int FACULTY_ID { get; set; }
        public string FACULTY_NAME { get; set; }
    
        public virtual ICollection<AVAILABLE_COURSE> AVAILABLE_COURSE { get; set; }
        public virtual ICollection<COURSE_TABLE> COURSE_TABLE { get; set; }
    }
}
