//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcDemo.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SFS : DbContext
    {
        public SFS()
            : base("name=SFS")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<AVAILABLE_COURSE> AVAILABLE_COURSE { get; set; }
        public DbSet<CAMPUS_TABLE> CAMPUS_TABLE { get; set; }
        public DbSet<COURSE_TABLE> COURSE_TABLE { get; set; }
        public DbSet<DETAILED_ETHINICITY_TABLE> DETAILED_ETHINICITY_TABLE { get; set; }
        public DbSet<ETHINICITY_TABLE> ETHINICITY_TABLE { get; set; }
        public DbSet<FACULTY_TABLE> FACULTY_TABLE { get; set; }
        public DbSet<STUDENT> STUDENTS { get; set; }
        public DbSet<UserProfile> UserProfiles { get; set; }
        public DbSet<VOUCHER_TABLE> VOUCHER_TABLE { get; set; }
        public DbSet<VOUCHER_TYPE_TABLLE> VOUCHER_TYPE_TABLLE { get; set; }
        public DbSet<webpages_Membership> webpages_Membership { get; set; }
        public DbSet<webpages_OAuthMembership> webpages_OAuthMembership { get; set; }
        public DbSet<webpages_Roles> webpages_Roles { get; set; }
    }
}
