//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcDemo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VOUCHER_TABLE
    {
        public int REF_NUM { get; set; }
        public string STUDENT_ID { get; set; }
        public int VOUCHER_TYPE_ID { get; set; }
        public Nullable<double> VOUCHER_VALUE { get; set; }
        public Nullable<double> KOHA_FUNDS { get; set; }
        public string ADVICE_DESCR { get; set; }
        public System.DateTime DATE_OF_ISSUE { get; set; }
    
        public virtual STUDENT STUDENT { get; set; }
        public virtual VOUCHER_TYPE_TABLLE VOUCHER_TYPE_TABLLE { get; set; }
    }
}
